// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPGManager.Desktop.Infra.Db.Contexts;

#nullable disable

namespace RPGManager.Desktop.SqLite.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251226220720_SqLite_v1_0_0_0")]
    partial class SqLite_v1_0_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.AbilityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(3)
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("AbilityScore");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Alignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("Alignment");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.CurrencyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("CurrencyTpe");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.DamageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("DamageType");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.GameSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<Guid?>("AlternativeAbilityScoreId")
                        .HasColumnType("text(36)");

                    b.Property<Guid>("BaseAbilityScoreId")
                        .HasColumnType("text(36)");

                    b.Property<Guid>("CurrencyTypeId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<float?>("RangeLong")
                        .HasColumnType("REAL");

                    b.Property<float?>("RangeNormal")
                        .HasColumnType("REAL");

                    b.Property<Guid>("WeaponCategoryId")
                        .HasColumnType("text(36)");

                    b.Property<Guid?>("WeaponTypeId")
                        .IsRequired()
                        .HasColumnType("text(36)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AlternativeAbilityScoreId");

                    b.HasIndex("BaseAbilityScoreId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("GameSystemId");

                    b.HasIndex("WeaponCategoryId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("WeaponCategory");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperties", b =>
                {
                    b.Property<Guid>("WeaponPropertyId")
                        .HasColumnType("text(36)");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("text(36)");

                    b.HasKey("WeaponPropertyId", "WeaponId");

                    b.HasIndex("WeaponId");

                    b.ToTable("WeaponProperties");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<Guid>("AlterantiveAbilityScoreId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<bool>("HasAlternativeDiceTypeDamage")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("WeaponProperty");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("WeaponType");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<string>("Alphabet")
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameSystemId");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text(36)");

                    b.Property<Guid>("BaseAbilityScoreId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("text(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaseAbilityScoreId");

                    b.HasIndex("GameSystemId");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.AbilityScore", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("AbilityScores")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Alignment", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Alignments")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.CurrencyType", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("CurrencyTypes")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.DamageType", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("DamageTypes")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.AbilityScore", "AlternativeAbilityScore")
                        .WithMany("AlternativeWeapons")
                        .HasForeignKey("AlternativeAbilityScoreId");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.AbilityScore", "BaseAbilityScore")
                        .WithMany("Weapons")
                        .HasForeignKey("BaseAbilityScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGManager.Desktop.Domain.Entities.CurrencyType", "CurrencyType")
                        .WithMany("Weapons")
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Weapons")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", "WeaponCategory")
                        .WithMany("Weapons")
                        .HasForeignKey("WeaponCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", "WeaponType")
                        .WithMany("Weapons")
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativeAbilityScore");

                    b.Navigation("BaseAbilityScore");

                    b.Navigation("CurrencyType");

                    b.Navigation("GameSystem");

                    b.Navigation("WeaponCategory");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("WeaponCategories")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperties", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", "Weapon")
                        .WithMany("Properties")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", "WeaponProperty")
                        .WithMany("Weapons")
                        .HasForeignKey("WeaponPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Weapon");

                    b.Navigation("WeaponProperty");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("WeaponProperties")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("WeaponTypes")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Language", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Languages")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Skill", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.AbilityScore", "BaseAbilityScore")
                        .WithMany("Skills")
                        .HasForeignKey("BaseAbilityScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Skills")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaseAbilityScore");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.AbilityScore", b =>
                {
                    b.Navigation("AlternativeWeapons");

                    b.Navigation("Skills");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.CurrencyType", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.GameSystem", b =>
                {
                    b.Navigation("AbilityScores");

                    b.Navigation("Alignments");

                    b.Navigation("CurrencyTypes");

                    b.Navigation("DamageTypes");

                    b.Navigation("Languages");

                    b.Navigation("Skills");

                    b.Navigation("WeaponCategories");

                    b.Navigation("WeaponProperties");

                    b.Navigation("WeaponTypes");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", b =>
                {
                    b.Navigation("Properties");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
