// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPGManager.Desktop.Infra.Db.Contexts;

#nullable disable

namespace RPGManager.Desktop.PostgreSql.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260320010127_PostgreSql_v1_0_0_0")]
    partial class PostgreSql_v1_0_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.AbilityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(3)
                        .HasColumnType("varchar")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_ability_score");

                    b.HasIndex("GameSystemId");

                    b.ToTable("ability_score");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Alignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_alignment");

                    b.HasIndex("GameSystemId");

                    b.ToTable("alignment");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_class");

                    b.ToTable("class");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.CurrencyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar")
                        .HasColumnName("abbreviation");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_currency_type");

                    b.HasIndex("GameSystemId");

                    b.ToTable("currency_type");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.DamageType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_damage_type");

                    b.HasIndex("GameSystemId");

                    b.ToTable("damage_type");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.GameSystem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_game_system");

                    b.ToTable("game_system");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseAbilityScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_ability_score_id");

                    b.Property<Guid?>("CurrencyTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("currency_type_id");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal")
                        .HasColumnName("price");

                    b.Property<float?>("RangeLong")
                        .HasColumnType("real")
                        .HasColumnName("range_long");

                    b.Property<float?>("RangeNormal")
                        .HasColumnType("real")
                        .HasColumnName("range_normal");

                    b.Property<Guid>("WeaponCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_category_id");

                    b.Property<Guid>("WeaponTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_type_id");

                    b.Property<float>("Weight")
                        .HasColumnType("real")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_k_weapon");

                    b.HasIndex("BaseAbilityScoreId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("GameSystemId");

                    b.HasIndex("WeaponCategoryId");

                    b.HasIndex("WeaponTypeId");

                    b.ToTable("weapon");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_weapon_category");

                    b.HasIndex("GameSystemId");

                    b.ToTable("weapon_category");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperties", b =>
                {
                    b.Property<Guid>("WeaponPropertyId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_property_id");

                    b.Property<Guid>("WeaponId")
                        .HasColumnType("uuid")
                        .HasColumnName("weapon_id");

                    b.HasKey("WeaponPropertyId", "WeaponId")
                        .HasName("p_k_weapon_properties");

                    b.HasIndex("WeaponId");

                    b.ToTable("weapon_properties");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlternativeAbilityScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("alternative_ability_score_id");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<bool>("HasAlternativeDiceTypeDamage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_alternative_dice_type_damage");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_weapon_property");

                    b.HasIndex("AlternativeAbilityScoreId");

                    b.HasIndex("GameSystemId");

                    b.ToTable("weapon_property");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_weapon_type");

                    b.HasIndex("GameSystemId");

                    b.ToTable("weapon_type");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alphabet")
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasColumnName("alphabet");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_language");

                    b.HasIndex("GameSystemId");

                    b.ToTable("language");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.RaceEntities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentRaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_race_id");

                    b.Property<float>("Speed")
                        .HasColumnType("real")
                        .HasColumnName("speed");

                    b.HasKey("Id")
                        .HasName("p_k_race");

                    b.HasIndex("GameSystemId");

                    b.HasIndex("ParentRaceId");

                    b.ToTable("race");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BaseAbilityScoreId")
                        .HasColumnType("uuid")
                        .HasColumnName("base_ability_score_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar")
                        .HasColumnName("description");

                    b.Property<Guid>("GameSystemId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_system_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_skill");

                    b.HasIndex("BaseAbilityScoreId");

                    b.HasIndex("GameSystemId");

                    b.ToTable("skill");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.AbilityScore", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("AbilityScores")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_ability_score__game_system_game_system_id");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Alignment", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Alignments")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_alignment__game_system_game_system_id");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.CurrencyType", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("CurrencyTypes")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_currency_type__game_system_game_system_id");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.DamageType", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("DamageTypes")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_damage_type__game_system_game_system_id");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.AbilityScore", "BaseAbilityScore")
                        .WithMany("Weapons")
                        .HasForeignKey("BaseAbilityScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon_ability_score_base_ability_score_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.CurrencyType", "CurrencyType")
                        .WithMany("Weapons")
                        .HasForeignKey("CurrencyTypeId")
                        .HasConstraintName("f_k_weapon_currency_type_currency_type_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Weapons")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon_game_system_game_system_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", "WeaponCategory")
                        .WithMany("Weapons")
                        .HasForeignKey("WeaponCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon__weapon_category_weapon_category_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", "WeaponType")
                        .WithMany("Weapons")
                        .HasForeignKey("WeaponTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon__weapon_type_weapon_type_id");

                    b.Navigation("BaseAbilityScore");

                    b.Navigation("CurrencyType");

                    b.Navigation("GameSystem");

                    b.Navigation("WeaponCategory");

                    b.Navigation("WeaponType");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("WeaponCategories")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon_category_game_system_game_system_id");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperties", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", "Weapon")
                        .WithMany("WeaponProperties")
                        .HasForeignKey("WeaponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon_properties_weapon_weapon_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", "WeaponProperty")
                        .WithMany("Weapons")
                        .HasForeignKey("WeaponPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon_properties__weapon_property_weapon_property_id");

                    b.Navigation("Weapon");

                    b.Navigation("WeaponProperty");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.AbilityScore", "AlternativeAbilityScore")
                        .WithMany("AlternativeAbilityScoreForWeaponProperties")
                        .HasForeignKey("AlternativeAbilityScoreId")
                        .HasConstraintName("f_k_weapon_property_ability_score_alternative_ability_score_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("WeaponProperties")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon_property_game_system_game_system_id");

                    b.Navigation("AlternativeAbilityScore");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("WeaponTypes")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_weapon_type_game_system_game_system_id");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Language", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Languages")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_language_game_system_game_system_id");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.RaceEntities.Race", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany()
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_race_game_system_game_system_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.RaceEntities.Race", "ParentRace")
                        .WithMany()
                        .HasForeignKey("ParentRaceId")
                        .HasConstraintName("f_k_race_race_parent_race_id");

                    b.Navigation("GameSystem");

                    b.Navigation("ParentRace");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.Skill", b =>
                {
                    b.HasOne("RPGManager.Desktop.Domain.Entities.AbilityScore", "BaseAbilityScore")
                        .WithMany("Skills")
                        .HasForeignKey("BaseAbilityScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_skill_ability_score_base_ability_score_id");

                    b.HasOne("RPGManager.Desktop.Domain.Entities.GameSystem", "GameSystem")
                        .WithMany("Skills")
                        .HasForeignKey("GameSystemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_skill_game_system_game_system_id");

                    b.Navigation("BaseAbilityScore");

                    b.Navigation("GameSystem");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.AbilityScore", b =>
                {
                    b.Navigation("AlternativeAbilityScoreForWeaponProperties");

                    b.Navigation("Skills");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.CurrencyType", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.GameSystem", b =>
                {
                    b.Navigation("AbilityScores");

                    b.Navigation("Alignments");

                    b.Navigation("CurrencyTypes");

                    b.Navigation("DamageTypes");

                    b.Navigation("Languages");

                    b.Navigation("Skills");

                    b.Navigation("WeaponCategories");

                    b.Navigation("WeaponProperties");

                    b.Navigation("WeaponTypes");

                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.Weapon", b =>
                {
                    b.Navigation("WeaponProperties");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponCategory", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponProperty", b =>
                {
                    b.Navigation("Weapons");
                });

            modelBuilder.Entity("RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities.WeaponType", b =>
                {
                    b.Navigation("Weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
