# Etapa 1: Renomear .yaml para .yml (recursivo)
Get-ChildItem -Path . -Filter "*.yaml" -Recurse | ForEach-Object {
    $newName = $_.Name -replace '\.yaml$', '.yml'
    Rename-Item -Path $_.FullName -NewName $newName
    Write-Host "Renomeado: $($_.Name) -> $newName"
}

# Etapa 2: Renomear arquivos para o nome do Gear (recursivo)
$renames = @{
    "01_acid.yml"                     = "Acid.yml"
    "02_alchemists_fire.yml"          = "Alchemist's Fire.yml"
    "03_antitoxin.yml"                = "Antitoxin.yml"
    "04_arcane_focus_crystal.yml"     = "Arcane Focus (Crystal).yml"
    "05_arcane_focus_orb.yml"         = "Arcane Focus (Orb).yml"
    "06_arcane_focus_rod.yml"         = "Arcane Focus (Rod).yml"
    "07_arcane_focus_staff.yml"       = "Arcane Focus (Staff).yml"
    "08_arcane_focus_wand.yml"        = "Arcane Focus (Wand).yml"
    "09_backpack.yml"                 = "Backpack.yml"
    "10_ball_bearings.yml"            = "Ball Bearings.yml"
    "11_barrel.yml"                   = "Barrel.yml"
    "12_basket.yml"                   = "Basket.yml"
    "13_bedroll.yml"                  = "Bedroll.yml"
    "14_bell.yml"                     = "Bell.yml"
    "15_blanket.yml"                  = "Blanket.yml"
    "16_block_and_tackle.yml"         = "Block and Tackle.yml"
    "17_book.yml"                     = "Book.yml"
    "18_bottle_glass.yml"             = "Bottle, Glass.yml"
    "19_bucket.yml"                   = "Bucket.yml"
    "20_burglar_pack.yml"             = "Burglar's Pack.yml"
    "21_caltrops.yml"                 = "Caltrops.yml"
    "22_candle.yml"                   = "Candle.yml"
    "23_case_crossbow_bolt.yml"       = "Case, Crossbow Bolt.yml"
    "24_case_map_scroll.yml"          = "Case, Map or Scroll.yml"
    "25_chain.yml"                    = "Chain.yml"
    "26_chest.yml"                    = "Chest.yml"
    "27_climbers_kit.yml"             = "Climber's Kit.yml"
    "28_clothes_fine.yml"             = "Clothes, Fine.yml"
    "29_clothes_travelers.yml"        = "Clothes, Traveler's.yml"
    "30_component_pouch.yml"          = "Component Pouch.yml"
    "31_costume.yml"                  = "Costume.yml"
    "32_crowbar.yml"                  = "Crowbar.yml"
    "33_diplomats_pack.yml"           = "Diplomat's Pack.yml"
    "34_druidic_focus_mistletoe.yml"  = "Druidic Focus (Sprig of Mistletoe).yml"
    "35_druidic_focus_staff.yml"      = "Druidic Focus (Wooden Staff).yml"
    "36_druidic_focus_yew_wand.yml"   = "Druidic Focus (Yew Wand).yml"
    "37_dungeoneers_pack.yml"         = "Dungeoneer's Pack.yml"
    "38_entertainers_pack.yml"        = "Entertainer's Pack.yml"
    "39_explorers_pack.yml"           = "Explorer's Pack.yml"
    "40_flask.yml"                    = "Flask.yml"
    "41_grappling_hook.yml"           = "Grappling Hook.yml"
    "42_healers_kit.yml"              = "Healer's Kit.yml"
    "43_holy_symbol_amulet.yml"       = "Holy Symbol (Amulet).yml"
    "44_holy_symbol_emblem.yml"       = "Holy Symbol (Emblem).yml"
    "45_holy_symbol_reliquary.yml"    = "Holy Symbol (Reliquary).yml"
    "46_holy_water.yml"               = "Holy Water.yml"
    "47_hunting_trap.yml"             = "Hunting Trap.yml"
    "48_ink.yml"                      = "Ink.yml"
    "49_ink_pen.yml"                  = "Ink Pen.yml"
    "50_jug.yml"                      = "Jug.yml"
    "51_ladder.yml"                   = "Ladder.yml"
    "52_lamp.yml"                     = "Lamp.yml"
    "53_lantern_bullseye.yml"         = "Lantern, Bullseye.yml"
    "54_lantern_hooded.yml"           = "Lantern, Hooded.yml"
    "55_lock.yml"                     = "Lock.yml"
    "56_magnifying_glass.yml"         = "Magnifying Glass.yml"
    "57_manacles.yml"                 = "Manacles.yml"
    "58_map.yml"                      = "Map.yml"
    "59_mirror.yml"                   = "Mirror.yml"
    "60_net.yml"                      = "Net.yml"
    "61_oil.yml"                      = "Oil.yml"
    "62_paper.yml"                    = "Paper.yml"
    "63_parchment.yml"                = "Parchment.yml"
    "64_perfume.yml"                  = "Perfume.yml"
    "65_poison_basic.yml"             = "Poison, Basic.yml"
    "66_pole.yml"                     = "Pole.yml"
    "67_pot_iron.yml"                 = "Pot, Iron.yml"
    "68_potion_of_healing.yml"        = "Potion of Healing.yml"
    "69_pouch.yml"                    = "Pouch.yml"
    "70_priests_pack.yml"             = "Priest's Pack.yml"
    "71_quiver.yml"                   = "Quiver.yml"
    "72_ram_portable.yml"             = "Ram, Portable.yml"
    "73_rations.yml"                  = "Rations.yml"
    "74_robe.yml"                     = "Robe.yml"
    "75_rope.yml"                     = "Rope.yml"
    "76_sack.yml"                     = "Sack.yml"
    "77_scholars_pack.yml"            = "Scholar's Pack.yml"
    "78_shovel.yml"                   = "Shovel.yml"
    "79_signal_whistle.yml"           = "Signal Whistle.yml"
    "80_spell_scroll_cantrip.yml"     = "Spell Scroll (Cantrip).yml"
    "81_spell_scroll_level1.yml"      = "Spell Scroll (Level 1).yml"
    "82_spikes_iron.yml"              = "Spikes, Iron.yml"
    "83_spyglass.yml"                 = "Spyglass.yml"
    "84_string.yml"                   = "String.yml"
    "85_tent.yml"                     = "Tent.yml"
    "86_tinderbox.yml"                = "Tinderbox.yml"
    "87_torch.yml"                    = "Torch.yml"
    "88_vial.yml"                     = "Vial.yml"
    "89_waterskin.yml"                = "Waterskin.yml"
}

Get-ChildItem -Path . -Filter "*.yml" -Recurse | ForEach-Object {
    if ($renames.ContainsKey($_.Name)) {
        Rename-Item -Path $_.FullName -NewName $renames[$_.Name]
        Write-Host "Renomeado: $($_.Name) -> $($renames[$_.Name])"
    }
}

Write-Host "`nConcluído!"