@startuml Weapon
entity WeaponCategory {
    Id: Guid <<PK>>
    GameSystemId: Guid <<FK>>
    Name: varchar 30
}

entity WeaponGroup {
    Id: Guid <<PK>>
    GameSystemId: Guid <<FK>>
    Name: varchar 30
}

entity WeaponProperty {
    Id: Guid <<PK>>
    GameSystemId: Guid <<FK>>
    Name: varchar 30
    Description: text
}

entity Weapon {
    Id: Guid <<PK>>
    GameSystemId: Guid <<FK>>
    WeaponCategoryId: Guid <<FK>>
    WeaponGroupId: Guid <<FK>> null
    Name: varchar 50
    Description: text null
    Cost: decimal(10,2)
    Weight: float
    DamageDieCount: int
    DamageDieType: int
    DamageType: varchar 30
    RangeNormal: int null
    RangeLong: int null
    ' IsFinesse: bit
    ' IsLight: bit
    ' IsHeavy: bit
    ' IsTwoHanded: bit
    ' IsVersatile: bit
    ' AlternativeDamageDieCount: int null
    ' AlternativeDamageDieType: int null
}

'entity DamageType {
'    Id: Guid <<PK>>
'    Name: varchar 30
'}

entity WeaponDamage {
    Id: Guid <<PK>>
    WeaponId: Guid <<FK>>
}

entity WeaponProperties {
    WeaponId: Guid <<PK>> <<FK>>
    WeaponPropertyId: Guid <<PK>> <<FK>>
    AlternativeDamageDieCount: int null
    AlternativeDamageDieType: int null
}

GameSystem -- WeaponCategory
GameSystem -- WeaponGroup
GameSystem -- Weapon
GameSystem -- WeaponProperty

WeaponCategory -- Weapon
WeaponGroup -- Weapon

Weapon -- WeaponProperties
WeaponProperty -- WeaponProperties
@enduml
