global using RPGManager.Desktop.Domain.Entities;
global using RPGManager.Desktop.Domain.Entities.ItemsEntities.WeaponEntities;
global using RPGManager.Desktop.Domain.Entities.RaceEntities;
global using RPGManager.Desktop.Domain.Interfaces.Mappers;
global using RPGManager.Desktop.Domain.Interfaces.Repositories;
global using RPGManager.Desktop.Domain.Interfaces.Services;
global using RPGManager.Desktop.Domain.Models;
global using RPGManager.Desktop.Domain.Models.Items.Weapons;
global using RPGManager.Desktop.Domain.Models.Races;